### ISSUE TITLE
Unable to stream audio since recent discord update

### ISSUE THREAD

**Issue by FConnuli** [m13253/discord-mic-bot#3]
Bot is properly receiving input in the lumeter but produces no audio on discord calls since a discord update.

**Comment by m13253** [comment]
Thanks for the report.
I haven’t been using Discord for a while, need to find a day to investigate this issue.

**Comment by booom313** [comment]
It seems like it doesn't properly get a call back that it's connected cause `voice_client.is_connected()` doesn't return true even when connected

**Comment by m13253** [comment]
> It seems like it doesn't properly get a call back that it's connected cause `voice_client.is_connected()` doesn't return true even when connected

If this is true, then it could be an issue in the [discord.py](https://github.com/Rapptz/discord.py) library.

**Comment by MatLemaitre99** [comment]
Same problem happened to me today. Any update planned or solution found ?

**Comment by m13253** [comment]
Unfortunately I don’t yet know how to fix it. Otherwise I would want to fix it.

**Comment by murmelgrumpf** [comment]
Had the same problem and simply upgrading the discord dependency via `pip install discord.py --upgrade` fixed my Problem. I don't know if upgrading discord.py[voice] also fixes it, but the above command certainly did it for me. 

Btw, thanks @m13253 for creating such an amazing and simple tool, really helps me out a lot.

**Comment by m13253** [comment]
Aah, so it indeed is an issue with the upstream dependency…

**Comment by booom313** [comment]
> Had the same problem and simply upgrading the discord dependency via `pip install discord.py --upgrade` fixed my Problem. I don't know if upgrading discord.py[voice] also fixes it, but the above command certainly did it for me.
> 
> Btw, thanks @m13253 for creating such an amazing and simple tool, really helps me out a lot.

What version of python are you using, as i tried said solution and the program just hangs after trying to run

**Comment by murmelgrumpf** [comment]
> 

Python 3.8.10
